server:
  servlet:
    context-path: /api/v1

spring:
  application:
    name: study-app

  datasource:
    url: jdbc:postgresql://localhost:5432/study
    username: study
    password: study123
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379
      password: redis123
      username: ""          # ← adiciona isso (Redis 7 exige explícito)
      timeout: 2000ms
      connect-timeout: 2000ms
      lettuce:
        pool:
          enabled: false
  rabbitmq:
    publisher-returns: true
    publisher-confirm-type: correlated
    host: ${HOST_RABBIT:localhost}
    port: 5672
    username: guest
    password: guest
    connection-timeout: 5000
    template:
      retry:
        enabled: false
        max-attempts: 3
        initial-interval: 1000
        multiplier: 2
        max-interval: 10000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        default_schema: study
        show_sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    schemas: study
    default-schema: study

jwt:
  secret: ${JWT_SECRET:dev-secret-key-must-be-at-least-256-bits-long!}
  access-token:
    expiration-minutes: ${JWT_ACCESS_EXPIRATION_MINUTES:10080}
  refresh-token:
    expiration-days: ${JWT_REFRESH_EXPIRATION_DAYS:30}

amqp:
  queue:
    user-created: user-created.queue
    notify-user: notify-user.queue
  dlq:
    user-created-dlq: user-created.dlq
    notify-user-dlq: notify-user.dlq

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate.type.descriptor.sql: TRACE
    com.seu.pacote: DEBUG

